### ISSUE TITLE
Skips over lines that only contain spaces/tabs.

### ISSUE THREAD

**Issue by azegallo** [xsleonard/sublime-MoveByParagraph#4]
Lines with spaces/tabs are skipped over.
You can just update `s = self.view.substr(line)`  on both lines 61 & 87 
to `s = self.view.substr(line).strip(" \t")`.

And thank you for creating this plugin! :+1:

**Comment by xsleonard** [comment]
You can make a pull request for it but I think it should be an option, I see some users want it to stop on whitespace and others don't.  I never noticed because I have `"trim_trailing_white_space_on_save": true` in my settings so there is never whitespace like that.
